#!/bin/bash
args=("$@")
ELEMENTS=${#args[@]}

input=""
output="default.dot"
flag=0;
verbose=0;

for (( i=0;i<$ELEMENTS;i++)); do
    arg=${args[${i}]}
    if [ ${arg:0:1} == '-' ]; then
        if [ ${arg:1:1} == 'h' ]; then
            echo "The correct usage is as follows :";
            echo ".\myASTGenerator -input=input.java -output=output.dot -verbose"
            exit 0
        fi
        if [ ${arg:1:1} = 'i' ]; then
            input=${arg:7};
            flag=1
        fi
        if [ ${arg:1:1} = 'o' ]; then
            output=${arg:8};
        fi
        if [ ${arg:1:1} = 'v' ]; then
            verbose=1;
        fi
    fi
done

if [ $flag == 0 ];then
    echo "Please enter input file or use -help to know syntax"
    exit
fi
if [ $verbose == 1 ];then
    cat parser.output
fi

# echo $input
# echo $output

./javacompiler $input
./newcompiler $input
mv out.dot $output

dot -Tpng -o image.png $output

rm -f *.output
