#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[496] =
    {   0,
        0,    0,  119,  117,    1,    1,    3,  117,  116,    5,
        7,  117,   10,   11,   12,   14,   17,   18,   22,   24,
      115,  115,   26,   28,   29,   33,   35,   41,   42,   43,
       44,   45,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  109,  110,  113,  114,    1,    4,    0,  115,    0,
      116,    6,    8,    9,    0,    0,   13,   15,   16,   19,
       20,   21,    0,  115,    0,    2,   25,    0,  115,  115,
      115,    0,  115,  115,  115,    0,    0,    0,    0,  115,
        0,   27,   30,   32,   34,   36,   37,   46,  116,  116,

      116,  116,  116,  116,  116,  116,  116,  116,   58,  116,
      116,  116,  116,  116,  116,  116,   68,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,   98,  116,  116,  116,
      116,  116,  116,  116,  111,  112,    0,    0,    0,    0,
        0,  115,    0,    0,    0,    0,    0,   23,    0,  115,
      115,  115,    0,    0,    0,    2,  115,    0,  115,  115,
      115,  115,  115,  115,    0,    0,  115,  115,  115,    0,
      115,  115,  115,    0,  115,   31,   38,   39,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  116,  116,  116,  116,  116,  116,   67,  116,  116,
       72,  116,  116,   76,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  101,  116,  103,  116,  116,
      116,  116,  116,    0,    0,    0,    0,    0,    0,    0,
        0,  115,  115,    0,  115,    0,    2,  115,    0,  115,
      115,    0,  115,  115,  115,  115,    0,    0,  115,  115,
        0,    0,  115,    0,    0,  115,    0,  115,    0,  115,
      115,    0,   40,  116,  116,  116,  116,   51,   52,  116,
       54,  116,  116,  116,  116,   60,   61,  116,  116,  116,

      116,  116,  116,  116,  116,  116,   74,  116,  115,   77,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,   95,  116,  116,  115,
      102,  104,  116,  116,  107,  116,    0,    0,    0,    0,
      115,    0,  115,    0,    0,  115,    0,  115,    0,    0,
      115,  115,    0,  115,  115,    0,  115,  116,  116,  116,
       50,   53,   55,  116,  116,  116,  116,  116,   64,   66,
      116,  116,  116,  116,  116,   78,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,   89,  116,  116,   92,
      116,  116,   96,  116,  116,  106,  108,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  115,  115,    0,
      115,  115,  116,   48,  116,  116,  116,   59,  116,  116,
      116,  116,   70,  116,  116,   75,  116,  116,  116,  116,
      116,   84,   85,  116,   87,   88,   90,  116,   93,  116,
       97,  116,  116,    0,    0,    0,  116,   49,  116,   57,
       62,   63,   65,  116,  116,  116,   79,   80,   81,  116,
      116,  116,  116,  116,  116,  116,  116,  115,   47,   56,
      116,  116,  116,  116,   83,   86,   91,  116,  116,  116,
      105,  116,  116,   73,   82,  116,   99,  116,   69,   71,
      116,  100,  116,   94,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   24,   24,   24,   25,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   33,   35,   36,   35,
        9,    9,    9,    9,    9,   37,    9,    9,    9,   38,
        9,    9,    9,    9,    9,    9,    9,   39,    9,    9,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,    9,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    5,    1,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1,    1,    6,    6,    6,    6,    7,    8,    3,    1,
        1,    1,    1,    9,    6,    6,    6,    6,    6,    6,
        3,    3,    3,    3,    7,    3,    3,    3,    8,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[510] =
    {   0,
        0,    0, 1046, 1047, 1047, 1040, 1015,   66,    0, 1014,
       64, 1001, 1047, 1047, 1012,   60, 1047,   61,   59,   72,
       92,  144, 1014, 1047,   57, 1010,   65, 1047, 1047, 1047,
     1047, 1009,   42,   38,   67,   51,   63,   79,   89,  979,
      978,   84,  976,  109,  985,  123,   91,  971,   99,   45,
      979, 1047,  106, 1047, 1047, 1047, 1047,  115, 1023,  197,
        0, 1047, 1047, 1047, 1018,  258, 1047, 1047, 1047, 1047,
     1047, 1047, 1010,  306, 1013,    0, 1047,  189,  341,  376,
      202,   81, 1047,  126, 1047,    0,  206,  129,    0,  212,
      250, 1047,  998, 1047, 1047, 1047,  153, 1047,  964,  963,

      966,  974,  959,  122,  976,  975,  962,  968,  953,  954,
      951,  138,  959,  956,  954,  950,    0,  951,  133,  952,
      960,  941,  951,  956,  957,  942,  145,  956,  185,  956,
      942,   60,  940,  945,  940,  154,    0,  219,  947,  934,
      100,  941,  930,  943, 1047, 1047,  286,  236,  163,  361,
      395, 1047,  250,  979,  978,  274,  288, 1047,  311,  323,
     1047,  266,  349,  974,  202,    0,  416,  383,  421,  290,
        0,    0, 1047, 1047,  431,  446,  331,  439,  463,  458,
      471,  472,    0,  498,  511, 1047, 1047,  959,  924,  937,
      930,  939,  934,  933,  934,  919,  917,  915,  932,  930,

      926,  918,  915,  923,  909,  925,  924,    0,  210,  905,
      916,  911,  852,    0,  845,  841,  838,  835,  817,  143,
      824,  820,  813,  812,  820,  813,  810,  819,  822,  807,
      822,  806,  809,  809,  816,    0,  802,    0,  808,  810,
      799,  800,  796,  535,  298,  243,  244,  406,  261,  411,
      838,  522,    0,  527,    0,  834, 1047,  538,  553,  568,
        0,  577,    0,    0,  573, 1047,  366,  267,  585, 1047,
      609,  600,  624,  628,  639,  621,  428,  637,  647,    0,
      665,  676, 1047,  787,  784,  794,  787,    0,    0,  760,
        0,  749,  755,  743,  751,    0,    0,  743,  746,  753,

      745,  736,  749,  736,  733,  716,    0,  718,    0,  710,
      726,  716,  722,  717,  712,  710,  701,  704,  695,  706,
      690,  699,  699,  683,  696,  686,    0,  671,  667,    0,
        0,    0,  665,  678,    0,  676,  310,  407,  455,  718,
      710,  692,    0,  707,  442,  726,  761,    0,  299,  584,
      766,    0,  771,    0,    0,  796,    0,  674,  655,  667,
        0,    0,    0,  654,  653,  658,  642,  655,  640,    0,
      637,  628,  625,  630,  629,    0,  626,  608,  607,  622,
      619,  607,  593,  578,  579,  587,    0,  579,  552,    0,
      559,  535,  523,  530,  526,    0,    0,  465,  579,  470,

      489,  517,  801,  805,    0,  635,  666,  809, 1047,  814,
        0,    0,  522,    0,  511,  503,  502,    0,  502,  494,
      486,  504,    0,  482,  483,    0,  475,  455,  465,  449,
      456,    0,    0,  455,    0,    0,    0,  453,    0,  443,
        0,  115,  444,  572,  839,  573,  426,    0,  425,    0,
        0,    0,    0,  404,  410,  375,    0,    0,    0,  372,
      347,  334,  322,  323,  322,  325,  312,  616,    0,    0,
      297,  291,  274,  269,    0,    0,    0,  260,  244,  228,
        0,  216,  226,    0,    0,  184,    0,  193,    0,    0,
      191,    0,  168,    0, 1047,  880,  887,  896,  905,  914,

      184,   71,  923,  928,  933,  942,  951,  955,  958
    } ;

static const flex_int16_t yy_def[510] =
    {   0,
      495,    1,  495,  495,  495,  495,  495,  496,  497,  495,
      495,  498,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  495,  495,  495,  495,  495,  495,  496,  495,  495,
      497,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  499,  500,  495,  495,  495,  495,
       80,  495,  495,  495,  495,  501,  495,  495,  502,   80,
      495,  495,  495,  495,  495,  495,  495,  495,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  495,  495,  495,  496,  496,  496,
      496,  495,  495,  495,  495,  495,  495,  495,  495,   74,
      495,  495,  495,  499,  503,  500,  495,  495,   79,  495,
       80,   81,  495,  495,  495,  495,  495,  504,   22,  179,
      495,  505,   90,  495,   22,  495,  495,  495,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  495,  506,  506,  496,  496,  496,  495,
      495,  495,  160,  495,   74,  507,  495,  495,  495,  495,
      169,  495,   80,   81,  495,  495,  495,  508,  504,  495,
      495,  269,   80,  495,  495,  495,  495,  505,  278,   90,
       90,  495,  495,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  506,  506,  506,  506,
      495,  495,  160,  507,  503,  495,  495,  169,  509,  495,
      495,  273,  495,  179,  281,  495,  185,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  506,  506,  506,

      506,  506,  506,  506,  340,  509,  509,  495,  495,  495,
      273,  281,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  506,  506,  506,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  506,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,    0,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495
    } ;

static const flex_int16_t yy_nxt[1121] =
    {   0,
        4,    5,    6,    5,    5,    5,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   29,    9,    9,    9,    9,    9,    9,    9,   30,
        4,   31,   32,    9,   33,   34,   35,   36,   37,   38,
        9,    9,   39,    9,   40,   41,   42,   43,   44,    9,
       45,   46,   47,   48,   49,   50,    9,   51,    9,   52,
       53,   54,   55,   59,   63,   68,  182,   73,   70,   74,
       74,   74,   74,   74,   93,   94,   75,   99,   69,   71,
       72,   76,   64,   96,   97,  101,  142,  143,  102,  108,

       77,  177,  177,  100,  227,  103,   60,   78,  109,   78,
       79,  104,   80,   80,   80,   80,   81,  110,  105,  111,
      228,  106,   85,  113,  107,   82,   83,   84,   85,  112,
       86,  114,  122,  115,  145,   87,  116,   88,  117,   83,
       84,   83,  136,  140,  118,  119,   85,  123,  137,  181,
      181,  138,  239,  125,  240,   60,  141,  126,   89,   78,
      173,   78,   79,  465,   90,   90,   90,   90,   90,  127,
       85,  130,  128,  173,  131,  173,  146,  466,   83,   84,
       85,  187,  188,  194,  195,  132,  133,   91,  134,  178,
      135,   83,   84,   83,  210,  211,  203,  219,   85,  148,

      204,  149,  220,   60,   58,  314,  232,  315,   58,  167,
      167,  167,  167,  167,  233,  494,  165,  150,  150,  150,
      151,  257,  172,  172,  172,  172,  179,  179,  179,  179,
      180,  222,  183,  183,  183,  183,  183,   58,  495,  493,
      247,  492,   58,   85,  223,  176,   58,  224,   85,   87,
      339,   85,  491,   58,  154,  184,  495,   58,   58,   58,
      153,  152,  154,  234,  303,  155,   85,  304,   85,  155,
      185,  185,  185,  185,  185,  490,   60,  489,  156,  156,
      156,  157,  235,  340,   60,  152,  236,  244,  245,  244,
      246,  244,  488,   91,  250,  250,  250,  250,  155,  152,

      161,   60,  338,  155,  271,  339,  487,  155,  251,  251,
      251,  251,  486,  161,  155,  161,  485,  339,  155,  155,
      155,  159,  484,  159,   83,  271,  160,  160,  160,  160,
      160,  252,  252,  252,  252,  252,  271,   83,  340,   83,
      161,  162,  407,  253,  253,  253,  253,  253,  483,  163,
      340,  265,  265,  161,  162,  161,  168,  271,  168,  482,
      481,  169,  169,  169,  169,  169,  254,  266,   85,  255,
      255,  255,  255,  255,  267,   83,  170,  480,  479,  478,
      477,  248,  248,  248,  248,  266,  265,  265,   83,  170,
       83,   78,  163,   78,   79,  476,  171,  171,  171,  171,

      172,   60,   85,  260,  260,  260,  260,  260,  475,  267,
      173,   84,  174,   85,  339,  249,  249,  249,  249,  175,
      474,  473,  152,  173,   84,  173,  249,  249,  249,  249,
      174,  251,  251,  251,  251,   60,  258,  258,  258,  258,
      258,  261,  261,  261,  261,  261,   60,  340,  276,  276,
      173,  263,  263,  263,  263,  264,  345,  268,  472,  259,
      471,  257,  398,  173,  262,  173,  264,  264,  264,  264,
      264,  277,   85,  470,  175,  270,  271,  339,   81,   81,
       81,   81,  272,  273,  273,  273,  273,   81,  469,  176,
      268,  276,  276,  270,  495,  340,  444,  271,  467,  174,

      464,  275,  463,  462,  461,  340,  274,  266,  270,  271,
      340,  460,  495,  459,  277,  279,  458,  174,  280,  280,
      280,  280,  280,  457,  339,  266,  270,  456,  455,  340,
      271,  281,  281,  281,  281,  281,  244,  245,  244,  246,
      244,  184,  341,  341,  341,  341,  341,  343,  343,  343,
      343,  343,  454,  453,  282,  452,  161,  340,  258,  258,
      258,  258,  258,  451,  450,  342,  449,  448,  447,  161,
      254,  161,  173,  258,  258,  258,  258,  258,  443,  468,
      339,  259,  442,  400,  441,  173,  339,  173,  346,  346,
      346,  346,  346,  265,  265,  440,  259,  348,  348,  348,

      348,  348,   83,  268,  351,  351,  351,  351,  351,  266,
      439,  347,  340,  340,  438,   83,  267,   83,  495,  340,
      262,  270,  271,   85,  350,  437,  350,  266,  272,  351,
      351,  351,  351,  351,  436,  435,  495,  495,  434,  270,
      433,  276,  276,  271,  352,  352,  352,  352,  354,  354,
      354,  354,  180,  432,  495,  268,  340,  266,  495,  180,
      180,  180,  180,  180,  277,  495,  431,  353,  430,  429,
      428,  274,  271,  270,  271,  266,  427,  426,  407,  425,
      279,  424,  275,  495,  495,  355,  355,  355,  355,  355,
      423,  270,  422,  271,  421,  271,  357,  357,  357,  357,

      357,  495,  420,  495,  419,  495,  418,  417,  356,  407,
      416,  415,  341,  341,  341,  341,  341,  414,  413,  282,
      399,  345,  400,  397,  495,  401,  396,  395,  394,  402,
      341,  341,  341,  341,  341,  342,  393,  392,  403,  403,
      403,  404,  391,  390,  161,  389,  346,  346,  346,  346,
      346,  388,  387,  342,  386,  385,  384,  161,  405,  161,
       83,  383,  382,  402,  381,  380,  379,  402,  378,  347,
      377,  376,  375,   83,  402,   83,  374,  373,  402,  402,
      402,  346,  346,  346,  346,  346,  408,  408,  408,  408,
      408,  411,  411,  411,  411,  264,  372,  371,  370,  369,

      409,  330,  368,  367,  347,  366,  365,  364,  339,  410,
      363,  362,  339,  409,  353,  409,  412,  412,  412,  412,
      412,  445,  445,  445,  445,  446,  446,  446,  446,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  356,
      361,  340,  360,  409,  359,  340,  339,  358,  345,  152,
      336,  335,  410,  334,  333,  332,  409,  410,  409,  446,
      446,  446,  446,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  340,
       58,  313,   58,   58,   58,   58,   58,   58,   58,   61,
      312,  311,   61,   61,   61,   61,   65,  310,   65,  309,

       65,   65,   65,   65,   65,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  166,  308,  166,  166,  166,  166,
      166,  166,  166,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  269,  269,  269,  269,  269,  278,  278,  278,
      278,  278,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      349,  307,  349,  406,  306,  406,  406,  305,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  165,  152,
      152,  243,  242,  241,  238,  237,  231,  230,  229,  226,

      225,  221,  218,  217,  216,  215,  214,  213,  212,  209,
      208,  207,  206,  205,  202,  201,  200,  199,  198,  197,
      196,  193,  192,  191,  190,  189,  186,  165,  158,  152,
      147,  144,  139,  129,  124,  121,  120,   98,   95,   92,
       67,   66,   62,   57,   56,  495,    3,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495
    } ;

static const flex_int16_t yy_chk[1121] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,   11,   16,  502,   19,   18,   19,
       19,   19,   19,   19,   25,   25,   20,   33,   16,   18,
       18,   20,   11,   27,   27,   34,   50,   50,   34,   36,

       20,   82,   82,   33,  132,   34,    8,   21,   36,   21,
       21,   35,   21,   21,   21,   21,   21,   37,   35,   37,
      132,   35,   58,   38,   35,   21,   21,   21,   21,   37,
       21,   38,   42,   38,   53,   21,   38,   21,   39,   21,
       21,   21,   47,   49,   39,   39,   21,   42,   47,   88,
       88,   47,  141,   44,  141,   58,   49,   44,   21,   22,
       84,   22,   22,  442,   22,   22,   22,   22,   22,   44,
      149,   46,   44,   84,   46,   84,   53,  442,   22,   22,
       22,   97,   97,  104,  104,   46,   46,   22,   46,  501,
       46,   22,   22,   22,  119,  119,  112,  127,   22,   60,

      112,   60,  127,  149,   60,  220,  136,  220,   60,   78,
       78,   78,   78,   78,  136,  493,  165,   60,   60,   60,
       60,  165,   81,   81,   81,   81,   87,   87,   87,   87,
       87,  129,   90,   90,   90,   90,   90,   60,   81,  491,
      148,  488,   60,  148,  129,   81,   60,  129,   90,   87,
      246,  247,  486,   60,  153,   90,   81,   60,   60,   60,
       66,  153,   66,  138,  209,   66,   90,  209,  249,   66,
       91,   91,   91,   91,   91,  483,  148,  482,   66,   66,
       66,   66,  138,  246,  247,  156,  138,  147,  147,  147,
      147,  147,  480,   91,  156,  156,  156,  156,   66,  157,

      162,  249,  245,   66,  268,  245,  479,   66,  157,  157,
      157,  157,  478,  162,   66,  162,  474,  337,   66,   66,
       66,   74,  473,   74,  170,  268,   74,   74,   74,   74,
       74,  159,  159,  159,  159,  159,  349,  170,  245,  170,
       74,   74,  349,  160,  160,  160,  160,  160,  472,   74,
      337,  177,  177,   74,   74,   74,   79,  349,   79,  471,
      467,   79,   79,   79,   79,   79,  160,  177,  150,  163,
      163,  163,  163,  163,  177,   79,   79,  466,  465,  464,
      463,  150,  150,  150,  150,  177,  267,  267,   79,   79,
       79,   80,  163,   80,   80,  462,   80,   80,   80,   80,

       80,  150,  151,  168,  168,  168,  168,  168,  461,  267,
       80,   80,   80,  248,  338,  151,  151,  151,  151,   80,
      460,  456,  250,   80,   80,   80,  248,  248,  248,  248,
       80,  250,  250,  250,  250,  151,  167,  167,  167,  167,
      167,  169,  169,  169,  169,  169,  248,  338,  277,  277,
      167,  175,  175,  175,  175,  175,  345,  178,  455,  167,
      454,  345,  339,  167,  169,  167,  176,  176,  176,  176,
      176,  277,  398,  449,  175,  178,  178,  400,  180,  180,
      180,  180,  178,  179,  179,  179,  179,  179,  447,  176,
      182,  181,  181,  178,  180,  339,  401,  178,  443,  179,

      440,  180,  438,  434,  431,  398,  179,  181,  182,  182,
      400,  430,  180,  429,  181,  182,  428,  179,  184,  184,
      184,  184,  184,  427,  402,  181,  182,  425,  424,  401,
      182,  185,  185,  185,  185,  185,  244,  244,  244,  244,
      244,  184,  252,  252,  252,  252,  252,  254,  254,  254,
      254,  254,  422,  421,  185,  420,  252,  402,  258,  258,
      258,  258,  258,  419,  417,  252,  416,  415,  413,  252,
      254,  252,  258,  259,  259,  259,  259,  259,  395,  444,
      446,  258,  394,  399,  393,  258,  399,  258,  260,  260,
      260,  260,  260,  265,  265,  392,  259,  262,  262,  262,

      262,  262,  260,  269,  350,  350,  350,  350,  350,  265,
      391,  260,  444,  446,  389,  260,  265,  260,  272,  399,
      262,  269,  269,  468,  271,  388,  271,  265,  269,  271,
      271,  271,  271,  271,  386,  385,  272,  272,  384,  269,
      383,  276,  276,  269,  273,  273,  273,  273,  274,  274,
      274,  274,  274,  382,  272,  278,  468,  276,  272,  275,
      275,  275,  275,  275,  276,  279,  381,  273,  380,  379,
      378,  274,  406,  278,  278,  276,  377,  375,  406,  374,
      278,  373,  275,  279,  279,  281,  281,  281,  281,  281,
      372,  278,  371,  406,  369,  278,  282,  282,  282,  282,

      282,  279,  368,  407,  367,  279,  366,  365,  281,  407,
      364,  360,  342,  342,  342,  342,  342,  359,  358,  282,
      340,  344,  340,  336,  407,  340,  334,  333,  329,  340,
      341,  341,  341,  341,  341,  342,  328,  326,  340,  340,
      340,  340,  325,  324,  341,  323,  346,  346,  346,  346,
      346,  322,  321,  341,  320,  319,  318,  341,  340,  341,
      346,  317,  316,  340,  315,  314,  313,  340,  312,  346,
      311,  310,  308,  346,  340,  346,  306,  305,  340,  340,
      340,  347,  347,  347,  347,  347,  351,  351,  351,  351,
      351,  353,  353,  353,  353,  353,  304,  303,  302,  301,

      351,  300,  299,  298,  347,  295,  294,  293,  403,  351,
      292,  290,  404,  351,  353,  351,  356,  356,  356,  356,
      356,  403,  403,  403,  403,  404,  404,  404,  404,  408,
      408,  408,  408,  408,  410,  410,  410,  410,  410,  356,
      287,  403,  286,  408,  285,  404,  445,  284,  256,  251,
      243,  242,  408,  241,  240,  239,  408,  410,  408,  445,
      445,  445,  445,  237,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  445,
      496,  219,  496,  496,  496,  496,  496,  496,  496,  497,
      218,  217,  497,  497,  497,  497,  498,  216,  498,  215,

      498,  498,  498,  498,  498,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  500,  213,  500,  500,  500,  500,
      500,  500,  500,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  504,  504,  504,  504,  504,  505,  505,  505,
      505,  505,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      508,  212,  508,  509,  211,  509,  509,  210,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  164,  155,
      154,  144,  143,  142,  140,  139,  135,  134,  133,  131,

      130,  128,  126,  125,  124,  123,  122,  121,  120,  118,
      116,  115,  114,  113,  111,  110,  109,  108,  107,  106,
      105,  103,  102,  101,  100,   99,   93,   75,   73,   65,
       59,   51,   48,   45,   43,   41,   40,   32,   26,   23,
       15,   12,   10,    7,    6,    3,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[119] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/prob2.l"
#line 3 "src/prob2.l"
#include "parser.tab.h"
extern int yylineno;
#line 904 "src/lex.yy.c"
#line 905 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 105 "src/prob2.l"

#line 1134 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 496 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1047 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 106 "src/prob2.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 107 "src/prob2.l"
{;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 109 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_33;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 110 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_3361;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 111 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_37;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 112 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_3761;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 113 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_38;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 114 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_3838;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 115 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_3861;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 116 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_40;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 117 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_41;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 118 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_42;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 119 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4261;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_43;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 121 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4343;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4361;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 123 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_44;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 124 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_45;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 125 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4545;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 126 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4561;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 127 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4562;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 128 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_46;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 129 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_464646;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 130 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_47;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 131 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_4761;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 132 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_58;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 133 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_5858;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_59;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 135 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_60;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 136 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_6060;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 137 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_606061;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 138 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_6061;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 139 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_61;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 140 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_6161;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 141 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_62;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 142 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_6261;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 143 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_6262;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 144 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_626261;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 145 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_626262;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 146 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_62626261;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 147 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_63;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 148 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_64;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_91;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 150 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_93;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 151 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_94;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 152 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_9461;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 153 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_abstract;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 154 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_assert;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 155 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_boolean;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 156 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_break;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 157 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_byte;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 158 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_case;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 159 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_catch;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 160 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_char;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 161 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_class;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 162 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_continue;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 163 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_default;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 164 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_do;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 165 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_double;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 166 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_else;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 167 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_enum;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_exports;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 169 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_extends;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_final;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 171 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_finally;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 172 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_float;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 173 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_for;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 174 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_if;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 175 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_implements;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 176 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_import;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 177 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_instanceof;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 178 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_int;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 179 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_interface;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 180 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_long;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 181 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_module;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 182 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_new;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 183 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_open;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 184 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_opens;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 185 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_package;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 186 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_permits;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 187 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_private;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 188 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_protected;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 189 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_provides;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 190 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_public;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 191 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_record;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 192 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_requires;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 193 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_return;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 194 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_sealed;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 195 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_short;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 196 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_static;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 197 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_strictfp;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 198 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_super;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 199 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_switch;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 200 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_synchronized;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 201 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_this;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 202 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_throw;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 203 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_throws;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 204 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_to;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 205 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_transient;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 206 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_transitive;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 207 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_try;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 208 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_uses;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 209 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_var;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 210 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_void;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 211 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_volatile;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 212 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_while;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 213 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_with;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 214 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_yield;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 215 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_123;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 216 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_124;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 217 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_12461;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 218 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_124124;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 219 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_125;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 220 "src/prob2.l"
{yylval->s=strdup(yytext);return TOK_126;}
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
#line 223 "src/prob2.l"
{yylval->s = strdup(yytext);return TOK_LITERAL;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 224 "src/prob2.l"
{yylval->s = strdup(yytext);return TOK_IDENTIFIER;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 225 "src/prob2.l"
{;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 226 "src/prob2.l"
ECHO;
	YY_BREAK
#line 1794 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 496 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 496 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 495);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 226 "src/prob2.l"




