#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[461] =
    {   0,
        0,    0,  110,  108,    1,    1,    3,  108,  107,    5,
        7,  108,   10,   11,   12,   14,   17,   18,   22,   24,
      105,  105,   26,   28,   29,   33,   35,   41,   42,   43,
       44,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,   99,  100,  103,
      104,    1,    4,    0,  106,    0,  107,    6,    8,    9,
        0,    0,   13,   15,   16,   19,   20,   21,    0,  105,
        0,    2,   25,    0,  105,  105,  105,    0,  105,  105,
      105,    0,    0,    0,    0,  105,    0,   27,   30,   32,
       34,   36,   37,   45,  107,  107,  107,  107,  107,  107,

      107,  107,  107,  107,   57,  107,  107,  107,  107,  107,
      107,  107,   66,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  101,  102,  106,    0,    0,
        0,    0,    0,  105,    0,    0,    0,    0,    0,   23,
        0,  105,  105,  105,    0,    0,    0,    2,  105,    0,
      105,  105,  105,  105,  105,  105,    0,    0,  105,  105,
      105,    0,  105,  105,  105,    0,  105,   31,   38,   39,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,   65,  107,

      107,   70,  107,   73,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,   93,   94,  107,  107,  107,  107,    0,
        0,    0,    0,    0,    0,    0,    0,  105,  105,    0,
      105,    0,    2,  105,    0,  105,  105,    0,  105,  105,
      105,  105,    0,    0,  105,  105,    0,    0,  105,    0,
        0,  105,    0,  105,    0,  105,  105,    0,   40,  107,
      107,  107,  107,   50,   51,  107,   53,  107,  107,  107,
      107,   59,   60,  107,  107,  107,  107,  107,  107,  107,
      107,   72,  106,  107,  107,  107,  107,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  107,   88,  107,  107,
      105,   95,  107,  107,  107,    0,    0,    0,    0,  105,
        0,  105,    0,    0,  105,    0,  105,    0,    0,  105,
      105,    0,  105,  105,    0,  105,  107,  107,  107,   49,
       52,   54,  107,  107,  107,  107,   62,   64,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
       82,  107,  107,   85,  107,  107,   89,  107,  107,   97,
       98,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  105,  105,    0,  105,  105,  107,   47,  107,  107,
      107,   58,  107,  107,  107,   68,  107,  107,  107,  107,

      107,  107,   78,   79,   80,   81,   83,  107,   86,  107,
       90,  107,  107,    0,    0,    0,  107,   48,  107,   56,
       61,   63,  107,  107,  107,   74,   75,   76,  107,  107,
      107,  107,  107,  107,  106,   46,   55,  107,  107,  107,
      107,   84,  107,  107,  107,   96,  107,  107,   71,   77,
      107,   91,  107,   67,   69,  107,   92,  107,   87,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   24,   24,   24,   25,   25,   26,   27,   28,
       29,   30,   31,    1,   32,   33,   32,   34,   35,   34,
        9,    9,    9,    9,    9,   36,    9,    9,    9,   37,
        9,    9,    9,    9,    9,    9,    9,   38,    9,    9,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,    9,   53,   54,   55,   56,
       57,   58,    9,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    5,    1,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1,    6,    6,    6,    6,    7,    8,    3,    1,    1,
        1,    1,    9,    6,    6,    6,    6,    6,    6,    3,
        3,    3,    3,    7,    3,    3,    3,    8,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[475] =
    {   0,
        0,    0, 1012, 1013, 1013, 1006,  981,   64,    0,  980,
       62,  968, 1013, 1013,  978,   58, 1013,   59,   57,   70,
       89,  139,  980, 1013,   55,  976,   63, 1013, 1013, 1013,
      975,   41,   37,   91,   49,   44,   74,   84,  946,   54,
      108,  954,  117,   70,   73,  950,  948, 1013,   46, 1013,
     1013, 1013, 1013,  111,  991,  191,    0, 1013, 1013, 1013,
      986,  250, 1013, 1013, 1013, 1013, 1013, 1013,  978,  296,
      981,    0, 1013,  183,  330,  364,  202,  125, 1013,  142,
     1013,    0,  196,  128,    0,  242,  258, 1013,  966, 1013,
     1013, 1013,  142, 1013,  934,  933,  935,  943,  929,  124,

      945,  944,  931,  937,  923,  924,  921,  921,  927,  924,
      922,  919,    0,  919,  137,  920,  911,  920,  927,  913,
      138,  926,   98,  924,  908,  133,  861,  851,  845,  150,
      166,  836,  175,  842,  837, 1013, 1013, 1013,  320,  161,
      203,  350,  393, 1013,  225,  870,  869,  265,  281, 1013,
      311,  338, 1013,  199,  381,  865,  229,    0,  398,  345,
      405,  266,    0,    0, 1013, 1013,  413,  428,  418,  423,
      461,  452,  457,  471,    0,  495,  509, 1013, 1013,  850,
      817,  829,  822,  831,  826,  825,  826,  812,  810,  808,
      824,  815,  811,  803,  808,  795,  810,  809,    0,  200,

      791,  802,  797,    0,  792,  792,  774,  764,  764,  769,
      765,  759,  765,  759,  743,  751,  748,  733,  747,  732,
      733,  733,  740,    0,    0,  734,  736,  722,  721,  389,
      289,  251,  252,  518,  267,  446,  754,  522,    0,  538,
        0,  750, 1013,  551,  565,  580,    0,  588,    0,    0,
      514, 1013,  306,   83,  596, 1013,  619,  580,  624,  634,
      639,  630,  354,  649,  651,    0,  672,  677, 1013,  705,
      703,  713,  707,    0,    0,  705,    0,  695,  702,  690,
      697,    0,    0,  689,  695,  684,  676,  688,  670,  684,
      668,    0,    0,  681,  672,  678,  671,  666,  658,  657,

      666,  652,  660,  665,  651,  662,  655,    0,  640,  631,
        0,    0,  629,  641,  636,  268,  276,  417,  718,  710,
      725,    0,  666,  322,  748,  762,    0,  455,  597,  777,
        0,  785,    0,    0,  791,    0,  636,  618,  634,    0,
        0,    0,  620,  621,  626,  625,  617,    0,  614,  604,
      597,  600,  586,  569,  567,  580,  579,  577,  551,  559,
        0,  551,  534,    0,  542,  533,  531,  532,  531,    0,
        0,  423,  497,  447,  454,  456,  556,  809,    0,  466,
      512,  814, 1013,  819,    0,    0,  536,    0,  511,  504,
      493,    0,  493,  485,  500,    0,  482,  483,  474,  450,

      453,  438,    0,    0,    0,    0,    0,  416,    0,  389,
        0,  174,  390,  472,  843,  481,  382,    0,  362,    0,
        0,    0,  353,  360,  350,    0,    0,    0,  336,  299,
      300,  294,  295,  293,  483,    0,    0,  279,  281,  250,
      223,    0,  217,  207,  198,    0,  182,  192,    0,    0,
      167,    0,  168,    0,    0,  152,    0,  133,    0, 1013,
      883,  890,  899,  908,  917,  147,   89,  926,  931,  936,
      945,  954,  958,  961
    } ;

static const flex_int16_t yy_def[475] =
    {   0,
      460,    1,  460,  460,  460,  460,  460,  461,  462,  460,
      460,  463,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  460,  460,  460,
      460,  460,  460,  461,  460,  460,  462,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      464,  465,  460,  460,  460,  460,   76,  460,  460,  460,
      460,  466,  460,  460,  467,   76,  460,  460,  460,  460,
      460,  460,  460,  460,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  460,  460,  460,  460,  461,
      461,  461,  461,  460,  460,  460,  460,  460,  460,  460,
      460,   70,  460,  460,  460,  464,  468,  465,  460,  460,
       75,  460,   76,   77,  460,  460,  460,  460,  460,  469,
       22,  171,  460,  470,   86,  460,   22,  460,  460,  460,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  460,
      471,  471,  461,  461,  461,  460,  460,  460,  152,  460,
       70,  472,  460,  460,  460,  460,  161,  460,   76,   77,
      460,  460,  460,  473,  469,  460,  460,  255,   76,  460,
      460,  460,  460,  470,  264,   86,   86,  460,  460,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  471,  471,  471,  471,  460,
      460,  152,  472,  468,  460,  460,  161,  474,  460,  460,
      259,  460,  171,  267,  460,  177,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  471,  471,  471,  471,  471,  471,  471,  319,  474,
      474,  460,  460,  460,  259,  267,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  471,  471,  471,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  471,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,    0,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460
    } ;

static const flex_int16_t yy_nxt[1085] =
    {   0,
        4,    5,    6,    5,    5,    5,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,    9,    9,    9,    9,    9,    9,    9,   29,    4,
       30,   31,    9,   32,   33,   34,   35,   36,   37,    9,
        9,   38,    9,   39,    9,   40,    9,   41,   42,   43,
       44,    9,   45,   46,    9,   47,    9,   48,   49,   50,
       51,   55,   59,   64,  136,   69,   66,   70,   70,   70,
       70,   70,   89,   90,   71,   95,   65,   67,   68,   72,
       60,   92,   93,   97,  174,   98,  104,  106,   73,  107,

       96,  117,   99,   56,   74,  105,   74,   75,  108,   76,
       76,   76,   76,   77,  137,  118,  132,  109,  138,  257,
      130,   78,   79,   80,   81,  110,   82,  111,  131,  133,
      112,   83,  113,   84,  100,   79,   80,   79,  114,  115,
      257,  101,   81,  211,  102,  169,  169,  103,  173,  173,
       56,  119,  170,   85,   74,  120,   74,   75,  212,   86,
       86,   86,   86,   86,  124,  233,  121,  125,  138,  122,
      179,  180,   79,   80,   81,  165,  215,  126,  127,  459,
      128,   87,  129,  186,  187,   79,   80,   79,  165,  208,
      165,  216,   81,  140,  209,  141,  201,  202,   54,  458,

       56,  220,   54,  159,  159,  159,  159,  159,  221,  222,
      138,  142,  142,  142,  143,  457,  171,  171,  171,  171,
      172,  432,  164,  164,  164,  164,  226,  223,  227,  146,
       54,  224,  153,  456,  433,   54,  144,  460,   83,   54,
      455,  454,   56,  157,  168,  153,   54,  153,  243,   54,
       54,   54,  145,  288,  146,  460,  289,  147,  318,  138,
      453,  147,  175,  175,  175,  175,  175,  452,  451,  450,
      148,  148,  148,  149,  138,  318,  144,   81,  177,  177,
      177,  177,  177,  318,  176,  236,  236,  236,  236,  147,
      319,   56,  144,  317,  147,   81,  318,  449,  147,   79,

       87,  237,  237,  237,  237,  147,   56,  319,  147,  147,
      147,  151,   79,  151,   79,  319,  152,  152,  152,  152,
      152,  230,  231,  230,  232,  230,  251,  251,  319,  153,
      154,  238,  238,  238,  238,  238,  324,  448,  155,  447,
      446,  243,  153,  154,  153,  160,  445,  160,  253,  444,
      161,  161,  161,  161,  161,  443,  442,  138,  239,  239,
      239,  239,  239,   79,  162,  246,  246,  246,  246,  246,
      234,  234,  234,  234,  262,  262,   79,  162,   79,   74,
      240,   74,   75,  441,  163,  163,  163,  163,  164,   56,
      230,  231,  230,  232,  230,  440,  263,  165,   80,  166,

      138,  241,  241,  241,  241,  241,  167,  439,  438,  437,
      165,   80,  165,  235,  235,  235,  235,  166,  244,  244,
      244,  244,  244,  155,  372,  247,  247,  247,  247,  247,
      138,  165,   56,  249,  249,  249,  249,  250,  251,  251,
      245,  254,  436,  434,  165,  431,  165,  248,  250,  250,
      250,  250,  250,  252,  318,  167,  319,  144,  256,  257,
      253,  414,  319,  318,  430,  258,  237,  237,  237,  237,
      168,  252,   77,   77,   77,   77,  256,  262,  262,  435,
      257,  259,  259,  259,  259,   77,  319,  460,  318,  254,
      138,  257,  252,  319,  261,  319,  166,  381,  429,  263,

      428,  374,  257,  260,  318,  460,  256,  257,  381,  427,
      252,  319,  257,  265,  166,  266,  266,  266,  266,  266,
      319,  426,  319,  257,  256,  138,  425,  424,  257,  267,
      267,  267,  267,  267,  251,  251,  319,  176,  235,  235,
      235,  235,  320,  320,  320,  320,  320,  423,  460,  252,
      422,  268,  421,  420,  381,  153,  253,   56,  322,  322,
      322,  322,  322,  318,  321,  419,  418,  252,  153,  460,
      153,  244,  244,  244,  244,  244,  415,  415,  415,  415,
      240,  417,  413,  412,  165,  244,  244,  244,  244,  244,
      411,  410,  409,  245,  408,  319,  407,  165,  460,  165,

      325,  325,  325,  325,  325,  406,  405,  245,  327,  327,
      327,  327,  327,   79,  254,  460,  460,  330,  330,  330,
      330,  330,  326,  404,  403,  402,   79,  401,   79,  400,
      248,  256,  257,  460,  329,  399,  329,  460,  258,  330,
      330,  330,  330,  330,  331,  331,  331,  331,  398,  256,
      262,  262,  397,  257,  333,  333,  333,  333,  172,  172,
      172,  172,  172,  172,  396,  252,  332,  254,  395,  460,
      394,  393,  263,  392,  391,  390,  260,  389,  388,  387,
      324,  261,  371,  252,  256,  257,  460,  460,  370,  369,
      368,  265,  334,  334,  334,  334,  334,  336,  336,  336,

      336,  336,  256,  367,  460,  366,  257,  365,  460,  364,
      363,  362,  361,  360,  335,  359,  358,  357,  356,  268,
      373,  355,  374,  354,  353,  375,  352,  351,  350,  376,
      320,  320,  320,  320,  320,  349,  348,  347,  377,  377,
      377,  378,  311,  153,  346,  320,  320,  320,  320,  320,
      345,  344,  321,  343,  342,  341,  153,  379,  153,  340,
      339,  338,  376,  337,  324,  144,  376,  321,  325,  325,
      325,  325,  325,  376,  315,  314,  376,  376,  376,  313,
      312,   79,  325,  325,  325,  325,  325,  311,  310,  309,
      326,  308,  307,  306,   79,  305,   79,  382,  382,  382,

      382,  382,  304,  303,  326,  385,  385,  385,  385,  250,
      383,  386,  386,  386,  386,  386,  318,  302,  301,  384,
      300,  299,  298,  383,  297,  383,  296,  332,  295,  416,
      416,  416,  416,  335,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  294,  293,  292,  383,  319,  291,
      318,  290,  287,  286,  285,  284,  384,  283,  282,  281,
      383,  384,  383,  416,  416,  416,  416,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  157,
      144,  144,  319,   54,  229,   54,   54,   54,   54,   54,
       54,   54,   57,  228,  225,   57,   57,   57,   57,   61,

      219,   61,  218,   61,   61,   61,   61,   61,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  158,  217,  158,
      158,  158,  158,  158,  158,  158,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  255,  255,  255,  255,  255,
      264,  264,  264,  264,  264,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  328,  214,  328,  380,  213,  380,  380,
      210,  207,  206,  205,  204,  203,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  185,
      184,  183,  182,  181,  178,  157,  150,  144,  139,  135,

      134,  123,  116,   94,   91,   88,   63,   62,   58,   53,
       52,  460,    3,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460
    } ;

static const flex_int16_t yy_chk[1085] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,   11,   16,   49,   19,   18,   19,   19,   19,
       19,   19,   25,   25,   20,   32,   16,   18,   18,   20,
       11,   27,   27,   33,  467,   33,   35,   36,   20,   36,

       32,   40,   33,    8,   21,   35,   21,   21,   36,   21,
       21,   21,   21,   21,   49,   40,   45,   37,   54,  254,
       44,   21,   21,   21,   21,   37,   21,   37,   44,   45,
       37,   21,   38,   21,   34,   21,   21,   21,   38,   38,
      254,   34,   21,  123,   34,   78,   78,   34,   84,   84,
       54,   41,  466,   21,   22,   41,   22,   22,  123,   22,
       22,   22,   22,   22,   43,  140,   41,   43,  140,   41,
       93,   93,   22,   22,   22,   80,  126,   43,   43,  458,
       43,   22,   43,  100,  100,   22,   22,   22,   80,  121,
       80,  126,   22,   56,  121,   56,  115,  115,   56,  456,

      140,  130,   56,   74,   74,   74,   74,   74,  130,  131,
      141,   56,   56,   56,   56,  453,   83,   83,   83,   83,
       83,  412,   77,   77,   77,   77,  133,  131,  133,  145,
       56,  131,  154,  451,  412,   56,  145,   77,   83,   56,
      448,  447,  141,  157,   77,  154,   56,  154,  157,   56,
       56,   56,   62,  200,   62,   77,  200,   62,  232,  233,
      445,   62,   86,   86,   86,   86,   86,  444,  443,  441,
       62,   62,   62,   62,  235,  316,  148,   86,   87,   87,
       87,   87,   87,  317,   86,  148,  148,  148,  148,   62,
      232,  233,  149,  231,   62,   86,  231,  440,   62,  162,

       87,  149,  149,  149,  149,   62,  235,  316,   62,   62,
       62,   70,  162,   70,  162,  317,   70,   70,   70,   70,
       70,  139,  139,  139,  139,  139,  253,  253,  231,   70,
       70,  151,  151,  151,  151,  151,  324,  439,   70,  438,
      434,  324,   70,   70,   70,   75,  433,   75,  253,  432,
       75,   75,   75,   75,   75,  431,  430,  142,  152,  152,
      152,  152,  152,   75,   75,  160,  160,  160,  160,  160,
      142,  142,  142,  142,  263,  263,   75,   75,   75,   76,
      152,   76,   76,  429,   76,   76,   76,   76,   76,  142,
      230,  230,  230,  230,  230,  425,  263,   76,   76,   76,

      143,  155,  155,  155,  155,  155,   76,  424,  423,  419,
       76,   76,   76,  143,  143,  143,  143,   76,  159,  159,
      159,  159,  159,  155,  318,  161,  161,  161,  161,  161,
      372,  159,  143,  167,  167,  167,  167,  167,  169,  169,
      159,  170,  417,  413,  159,  410,  159,  161,  168,  168,
      168,  168,  168,  169,  374,  167,  318,  236,  170,  170,
      169,  375,  372,  376,  408,  170,  236,  236,  236,  236,
      168,  169,  172,  172,  172,  172,  170,  173,  173,  414,
      170,  171,  171,  171,  171,  171,  374,  172,  416,  174,
      435,  328,  173,  375,  172,  376,  171,  328,  402,  173,

      401,  373,  380,  171,  373,  172,  174,  174,  380,  400,
      173,  414,  328,  174,  171,  176,  176,  176,  176,  176,
      416,  399,  435,  380,  174,  234,  398,  397,  174,  177,
      177,  177,  177,  177,  251,  251,  373,  176,  234,  234,
      234,  234,  238,  238,  238,  238,  238,  395,  381,  251,
      394,  177,  393,  391,  381,  238,  251,  234,  240,  240,
      240,  240,  240,  377,  238,  390,  389,  251,  238,  381,
      238,  244,  244,  244,  244,  244,  377,  377,  377,  377,
      240,  387,  369,  368,  244,  245,  245,  245,  245,  245,
      367,  366,  365,  244,  363,  377,  362,  244,  258,  244,

      246,  246,  246,  246,  246,  360,  359,  245,  248,  248,
      248,  248,  248,  246,  255,  258,  258,  329,  329,  329,
      329,  329,  246,  358,  357,  356,  246,  355,  246,  354,
      248,  255,  255,  258,  257,  353,  257,  258,  255,  257,
      257,  257,  257,  257,  259,  259,  259,  259,  352,  255,
      262,  262,  351,  255,  260,  260,  260,  260,  260,  261,
      261,  261,  261,  261,  350,  262,  259,  264,  349,  265,
      347,  346,  262,  345,  344,  343,  260,  339,  338,  337,
      323,  261,  315,  262,  264,  264,  265,  265,  314,  313,
      310,  264,  267,  267,  267,  267,  267,  268,  268,  268,

      268,  268,  264,  309,  265,  307,  264,  306,  265,  305,
      304,  303,  302,  301,  267,  300,  299,  298,  297,  268,
      319,  296,  319,  295,  294,  319,  291,  290,  289,  319,
      320,  320,  320,  320,  320,  288,  287,  286,  319,  319,
      319,  319,  285,  320,  284,  321,  321,  321,  321,  321,
      281,  280,  320,  279,  278,  276,  320,  319,  320,  273,
      272,  271,  319,  270,  242,  237,  319,  321,  325,  325,
      325,  325,  325,  319,  229,  228,  319,  319,  319,  227,
      226,  325,  326,  326,  326,  326,  326,  223,  222,  221,
      325,  220,  219,  218,  325,  217,  325,  330,  330,  330,

      330,  330,  216,  215,  326,  332,  332,  332,  332,  332,
      330,  335,  335,  335,  335,  335,  378,  214,  213,  330,
      212,  211,  210,  330,  209,  330,  208,  332,  207,  378,
      378,  378,  378,  335,  382,  382,  382,  382,  382,  384,
      384,  384,  384,  384,  206,  205,  203,  382,  378,  202,
      415,  201,  198,  197,  196,  195,  382,  194,  193,  192,
      382,  384,  382,  415,  415,  415,  415,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  156,
      147,  146,  415,  461,  135,  461,  461,  461,  461,  461,
      461,  461,  462,  134,  132,  462,  462,  462,  462,  463,

      129,  463,  128,  463,  463,  463,  463,  463,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  465,  127,  465,
      465,  465,  465,  465,  465,  465,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  469,  469,  469,  469,  469,
      470,  470,  470,  470,  470,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  473,  125,  473,  474,  124,  474,  474,
      122,  120,  119,  118,  117,  116,  114,  112,  111,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,   99,
       98,   97,   96,   95,   89,   71,   69,   61,   55,   47,

       46,   42,   39,   31,   26,   23,   15,   12,   10,    7,
        6,    3,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[110] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 3 "scanner.l"
#include "grammer.tab.h"
// #include "parser.tab.h"

extern int yylineno;
#line 885 "lex.yy.c"
#line 886 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 108 "scanner.l"

#line 1115 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 461 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1013 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 109 "scanner.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 110 "scanner.l"
{;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 112 "scanner.l"
{yylval->s=strdup(yytext);return TOK_33;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "scanner.l"
{yylval->s=strdup(yytext);return TOK_3361;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 114 "scanner.l"
{yylval->s=strdup(yytext);return TOK_37;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 115 "scanner.l"
{yylval->s=strdup(yytext);return TOK_3761;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "scanner.l"
{yylval->s=strdup(yytext);return TOK_38;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 117 "scanner.l"
{yylval->s=strdup(yytext);return TOK_3838;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 118 "scanner.l"
{yylval->s=strdup(yytext);return TOK_3861;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 119 "scanner.l"
{yylval->s=strdup(yytext);return TOK_40;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 120 "scanner.l"
{yylval->s=strdup(yytext);return TOK_41;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 121 "scanner.l"
{yylval->s=strdup(yytext);return TOK_42;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 122 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4261;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 123 "scanner.l"
{yylval->s=strdup(yytext);return TOK_43;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 124 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4343;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 125 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4361;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 126 "scanner.l"
{yylval->s=strdup(yytext);return TOK_44;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 127 "scanner.l"
{yylval->s=strdup(yytext);return TOK_45;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 128 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4545;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 129 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4561;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 130 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4562;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 131 "scanner.l"
{yylval->s=strdup(yytext);return TOK_46;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 132 "scanner.l"
{yylval->s=strdup(yytext);return TOK_464646;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 133 "scanner.l"
{yylval->s=strdup(yytext);return TOK_47;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 134 "scanner.l"
{yylval->s=strdup(yytext);return TOK_4761;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 135 "scanner.l"
{yylval->s=strdup(yytext);return TOK_58;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 136 "scanner.l"
{yylval->s=strdup(yytext);return TOK_5858;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 137 "scanner.l"
{yylval->s=strdup(yytext);return TOK_59;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 138 "scanner.l"
{yylval->s=strdup(yytext);return TOK_60;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 139 "scanner.l"
{yylval->s=strdup(yytext);return TOK_6060;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 140 "scanner.l"
{yylval->s=strdup(yytext);return TOK_606061;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 141 "scanner.l"
{yylval->s=strdup(yytext);return TOK_6061;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 142 "scanner.l"
{yylval->s=strdup(yytext);return TOK_61;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 143 "scanner.l"
{yylval->s=strdup(yytext);return TOK_6161;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 144 "scanner.l"
{yylval->s=strdup(yytext);return TOK_62;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 145 "scanner.l"
{yylval->s=strdup(yytext);return TOK_6261;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 146 "scanner.l"
{yylval->s=strdup(yytext);return TOK_6262;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 147 "scanner.l"
{yylval->s=strdup(yytext);return TOK_626261;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 148 "scanner.l"
{yylval->s=strdup(yytext);return TOK_626262;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 149 "scanner.l"
{yylval->s=strdup(yytext);return TOK_62626261;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 150 "scanner.l"
{yylval->s=strdup(yytext);return TOK_63;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 151 "scanner.l"
{yylval->s=strdup(yytext);return TOK_91;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 152 "scanner.l"
{yylval->s=strdup(yytext);return TOK_93;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 153 "scanner.l"
{yylval->s=strdup(yytext);return TOK_94;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 154 "scanner.l"
{yylval->s=strdup(yytext);return TOK_9461;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 155 "scanner.l"
{yylval->s=strdup(yytext);return TOK_abstract;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 156 "scanner.l"
{yylval->s=strdup(yytext);return TOK_assert;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 157 "scanner.l"
{yylval->s=strdup(yytext);return TOK_boolean;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 158 "scanner.l"
{yylval->s=strdup(yytext);return TOK_break;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 159 "scanner.l"
{yylval->s=strdup(yytext);return TOK_byte;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 160 "scanner.l"
{yylval->s=strdup(yytext);return TOK_case;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 161 "scanner.l"
{yylval->s=strdup(yytext);return TOK_catch;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 162 "scanner.l"
{yylval->s=strdup(yytext);return TOK_char;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 163 "scanner.l"
{yylval->s=strdup(yytext);return TOK_class;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 164 "scanner.l"
{yylval->s=strdup(yytext);return TOK_continue;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 165 "scanner.l"
{yylval->s=strdup(yytext);return TOK_default;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 166 "scanner.l"
{yylval->s=strdup(yytext);return TOK_do;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "scanner.l"
{yylval->s=strdup(yytext);return TOK_double;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 168 "scanner.l"
{yylval->s=strdup(yytext);return TOK_else;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "scanner.l"
{yylval->s=strdup(yytext);return TOK_enum;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 170 "scanner.l"
{yylval->s=strdup(yytext);return TOK_extends;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 171 "scanner.l"
{yylval->s=strdup(yytext);return TOK_final;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 172 "scanner.l"
{yylval->s=strdup(yytext);return TOK_finally;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 173 "scanner.l"
{yylval->s=strdup(yytext);return TOK_float;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 174 "scanner.l"
{yylval->s=strdup(yytext);return TOK_for;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 175 "scanner.l"
{yylval->s=strdup(yytext);return TOK_if;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 176 "scanner.l"
{yylval->s=strdup(yytext);return TOK_implements;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 177 "scanner.l"
{yylval->s=strdup(yytext);return TOK_import;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 178 "scanner.l"
{yylval->s=strdup(yytext);return TOK_instanceof;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 179 "scanner.l"
{yylval->s=strdup(yytext);return TOK_int;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 180 "scanner.l"
{yylval->s=strdup(yytext);return TOK_interface;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 181 "scanner.l"
{yylval->s=strdup(yytext);return TOK_long;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 182 "scanner.l"
{yylval->s=strdup(yytext);return TOK_new;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 183 "scanner.l"
{yylval->s=strdup(yytext);return TOK_package;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 184 "scanner.l"
{yylval->s=strdup(yytext);return TOK_permits;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 185 "scanner.l"
{yylval->s=strdup(yytext);return TOK_private;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 186 "scanner.l"
{yylval->s=strdup(yytext);return TOK_protected;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 187 "scanner.l"
{yylval->s=strdup(yytext);return TOK_public;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 188 "scanner.l"
{yylval->s=strdup(yytext);return TOK_record;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 189 "scanner.l"
{yylval->s=strdup(yytext);return TOK_return;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 190 "scanner.l"
{yylval->s=strdup(yytext);return TOK_sealed;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 191 "scanner.l"
{yylval->s=strdup(yytext);return TOK_short;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 192 "scanner.l"
{yylval->s=strdup(yytext);return TOK_static;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 193 "scanner.l"
{yylval->s=strdup(yytext);return TOK_strictfp;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 194 "scanner.l"
{yylval->s=strdup(yytext);return TOK_super;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 195 "scanner.l"
{yylval->s=strdup(yytext);return TOK_switch;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 196 "scanner.l"
{yylval->s=strdup(yytext);return TOK_synchronized;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 197 "scanner.l"
{yylval->s=strdup(yytext);return TOK_this;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "scanner.l"
{yylval->s=strdup(yytext);return TOK_throw;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 199 "scanner.l"
{yylval->s=strdup(yytext);return TOK_throws;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 200 "scanner.l"
{yylval->s=strdup(yytext);return TOK_transient;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 201 "scanner.l"
{yylval->s=strdup(yytext);return TOK_transitive;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 202 "scanner.l"
{yylval->s=strdup(yytext);return TOK_try;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 203 "scanner.l"
{yylval->s=strdup(yytext);return TOK_var;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 204 "scanner.l"
{yylval->s=strdup(yytext);return TOK_void;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 205 "scanner.l"
{yylval->s=strdup(yytext);return TOK_volatile;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 206 "scanner.l"
{yylval->s=strdup(yytext);return TOK_while;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 207 "scanner.l"
{yylval->s=strdup(yytext);return TOK_yield;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 208 "scanner.l"
{yylval->s=strdup(yytext);return TOK_123;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 209 "scanner.l"
{yylval->s=strdup(yytext);return TOK_124;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 210 "scanner.l"
{yylval->s=strdup(yytext);return TOK_12461;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 211 "scanner.l"
{yylval->s=strdup(yytext);return TOK_124124;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 212 "scanner.l"
{yylval->s=strdup(yytext);return TOK_125;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 213 "scanner.l"
{yylval->s=strdup(yytext);return TOK_126;}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 215 "scanner.l"
{yylval->s = strdup(yytext);return TOK_NUMERICLITERAL;}
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 216 "scanner.l"
{yylval->s = strdup(yytext);return TOK_NONNUMERICLITERAL;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 217 "scanner.l"
{yylval->s = strdup(yytext);return TOK_IDENTIFIER;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 218 "scanner.l"
{;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 219 "scanner.l"
ECHO;
	YY_BREAK
#line 1731 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 461 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 461 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 460);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 219 "scanner.l"




